### PR TITLE
Add decipher.nvim

### PR DESCRIPTION
**Pull request by MisanthropicBit**
Link: https://github.com/MisanthropicBit/decipher.nvim

Thanks for dotfyle and migrating TWiN 🙂

### CODE REVIEW

**Comment by codicocodes** [comment]
Thank you for adding your plugin! :)

**Comment by codicocodes** [comment]
If you want the images in your readme to be parsed, you should not put the file in the repository. Instead you should upload the file to GitHub.

Upload the image to github and use the rawlink like so: `https://github.com/codicocodes/dotfyle/assets/76068197/b6aef30f-ce23-48d0-8684-402fdeb4c414`

image

**Comment by codicocodes** [comment]
Or use the permalink `https://github.com/MisanthropicBit/decipher.nvim/blob/95d5485b83572a8a6248ae97ac9fbd0078b3a2f1/decipher-demo.gif`

**Comment by MisanthropicBit** [comment]
Wow that was fast 😄 thanks for the tip, I'll make sure to update the repo.

**Comment by codicocodes** [comment]
No! I mean when you attached an image to e.g. a PR or a GitHub issue, github uploads the image and gives you a permaurl that you can use in the readme and Dotfyle can pick up.

It's generally a good practice to not put your assets directly in the plugin repository, because any user who downloads your plugin will have to download the media in the Readme as well.

By uploading it the GitHub CDN and using the permalink the users don't need to download the image when using the plugin!

**Comment by codicocodes** [comment]
@MisanthropicBit phaazon describes what I mean in more detail here https://www.reddit.com/r/neovim/comments/wsg5yx/attention_to_all_plugin_authors_newcomers_careful/

**Comment by MisanthropicBit** [comment]
What a neat trick, I've updated the repo as described now. Thanks for your help :)

**Pull request merged**
